# 02 - Data Cleaning

Inspect missing values, duplicates and data inconsistencies.

## Step 1: Load the Dataset

This cell imports the required libraries, loads the customer support dataset, and displays its dimensions.

In [1]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("../data/raw/customer_support_tickets.csv")

print("Dataset Loaded Successfully!")
print("-" * 40)

print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

Dataset Loaded Successfully!
----------------------------------------
Total Rows: 8469
Total Columns: 17

**Summary:** The dataset is loaded into a Pandas DataFrame. The row and column counts confirm that the file was read successfully.

## Step 2: Understand the Dataset

This cell previews sample records, checks column data types and non-null counts, and generates a statistical summary.

In [2]:
# First five records
display(df.head())

# Dataset information
df.info()

# Statistical summary
display(df.describe(include="all"))

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   object
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    2769 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   object
 15  Time to Resolution            2769 non-null   object
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), object(14)
memory usage: 1.1+ MB

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
count,8469.000000,8469,8469,8469.000000,8469,8469,8469,8469,8469,8469,8469,2769,8469,8469,5650,2769,2769.000000
unique,NaN,8028,8320,NaN,3,42,730,5,16,8077,3,2769,4,4,5470,2728,NaN
top,NaN,Michael Garcia,asmith@example.com,NaN,Male,Canon EOS,2020-10-21,Refund request,Refund request,I'm having an issue with the {product_purchase...,Pending Customer Response,We seat culture plan.,Medium,Email,2023-06-01 20:45:39,2023-06-01 17:14:42,NaN
freq,NaN,5,4,NaN,2896,240,24,1752,576,25,2881,1,2192,2143,3,3,NaN
mean,4235.000000,NaN,NaN,44.026804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.991333
std,2444.934048,NaN,NaN,15.296112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.407016
min,1.000000,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,2118.000000,NaN,NaN,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000
50%,4235.000000,NaN,NaN,44.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000
75%,6352.000000,NaN,NaN,57.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000
max,8469.000000,NaN,NaN,70.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000

**Summary:** These checks provide an initial understanding of the dataset's structure, values, and distribution.

## Step 3: Missing Value Analysis

This cell counts missing values in each column and calculates their percentage to identify incomplete fields.

In [3]:
# Missing value analysis

missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

missing_data = pd.DataFrame({
    'Missing Values': missing_count,
    'Missing Percentage': missing_percentage.round(2)
})

missing_data = missing_data[missing_data['Missing Values'] > 0]

print("MISSING VALUE ANALYSIS")
print("-" * 40)

display(missing_data.sort_values(
    by='Missing Values',
    ascending=False
))

MISSING VALUE ANALYSIS
----------------------------------------

                              Missing Values  Missing Percentage
Resolution                              5700               67.30
Time to Resolution                      5700               67.30
Customer Satisfaction Rating            5700               67.30
First Response Time                     2819               33.29

**Summary:** The analysis highlights columns with missing information. Missing values are retained rather than replaced with arbitrary values.

# DUPLICATES DETECTION

## Step 4: Duplicate Detection

This cell checks for duplicate rows and repeated Ticket IDs, and displays duplicates if any are found.

In [4]:
# 1. Check duplicate rows
duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

# 2. Check duplicate Ticket IDs
duplicate_ids = df['Ticket ID'].duplicated().sum()

print("Duplicate Ticket IDs:", duplicate_ids)

# 3. Display duplicates if available
if duplicate_rows > 0:
    display(df[df.duplicated(keep=False)])
else:
    print("No duplicate records found.")

if duplicate_ids > 0:
    display(df[df['Ticket ID'].duplicated(keep=False)])
else:
    print("All Ticket IDs are unique.")

Duplicate Rows: 0
Duplicate Ticket IDs: 0
No duplicate records found.
All Ticket IDs are unique.

**Summary:** This helps verify record uniqueness and prevents repeated tickets from affecting downstream analysis.

# INVALID VALUE DETECTION

## Step 5: Invalid Value Detection

This cell checks customer ages, satisfaction ratings, and numerical fields for values outside the expected ranges.

In [5]:
# 1. Customer Age validation

invalid_age = df[
    (df['Customer Age'] < 0) |
    (df['Customer Age'] > 120)
]

print("Invalid Customer Ages:", len(invalid_age))


# 2. Customer Satisfaction validation

invalid_rating = df[
    (df['Customer Satisfaction Rating'] < 1) |
    (df['Customer Satisfaction Rating'] > 5)
]

print("Invalid Satisfaction Ratings:", len(invalid_rating))


# 3. Check negative values in numerical columns

print("\nNegative Value Check:")

for col in ['Customer Age', 'Customer Satisfaction Rating']:
    print(col, ":", (df[col] < 0).sum())

Invalid Customer Ages: 0
Invalid Satisfaction Ratings: 0

Negative Value Check:
Customer Age : 0
Customer Satisfaction Rating : 0

**Summary:** The checks help identify potentially invalid records. The satisfaction rating range should be confirmed against the dataset's official definition.

# INCONSISTENT VALUES DETECTION

## Step 6: Inconsistent Value Detection

This cell reviews the unique values in key categorical columns and checks text fields for leading or trailing spaces.

In [7]:
# Categorical consistency check

columns = [
    'Ticket Status',
    'Ticket Priority',
    'Ticket Channel',
    'Ticket Type',
    'Customer Gender'
]

for col in columns:

    print("\n", col)
    print("-" * 30)

    print("Unique Values:", df[col].nunique())
    print(df[col].value_counts(dropna=False))

    print("\nWHITESPACE CHECK")

for col in df.select_dtypes(include='object').columns:

    count = df[col].dropna().apply(
        lambda x: x != x.strip()
    ).sum()

    if count > 0:
        print(col, ":", count, "inconsistent values")

print("Whitespace check completed.")

 Ticket Status
------------------------------
Unique Values: 3
Ticket Status
Pending Customer Response    2881
Open                         2819
Closed                       2769
Name: count, dtype: int64

WHITESPACE CHECK

 Ticket Priority
------------------------------
Unique Values: 4
Ticket Priority
Medium      2192
Critical    2129
High        2085
Low         2063
Name: count, dtype: int64

WHITESPACE CHECK

 Ticket Channel
------------------------------
Unique Values: 4
Ticket Channel
Email           2143
Phone           2132
Social media    2121
Chat            2073
Name: count, dtype: int64

WHITESPACE CHECK

 Ticket Type
------------------------------
Unique Values: 5
Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

WHITESPACE CHECK

 Customer Gender
------------------------------
Unique Values: 3
Customer Gender
Male      2896
Female    2887
Other     2686
Name: count, dtype: int64

WHITESPACE CHECK
Whitespace check completed.

**Summary:** This helps identify inconsistent category labels and formatting issues that could affect grouping and analysis.

# DATA TYPE VALIDATION

## Step 7: Data Type Validation

This cell inspects existing data types and converts date and numerical columns into suitable formats.

In [8]:
# Check current data types

print("CURRENT DATA TYPES")
print("-" * 35)

print(df.dtypes)

# Convert date columns
date_columns = [
    'Date of Purchase',
    'First Response Time',
    'Time to Resolution'
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

# Convert numerical columns
df['Customer Age'] = pd.to_numeric(
    df['Customer Age'], errors='coerce'
)

df['Customer Satisfaction Rating'] = pd.to_numeric(
    df['Customer Satisfaction Rating'], errors='coerce'
)

print("\nUPDATED DATA TYPES")
print("-" * 35)

print(df.dtypes)

CURRENT DATA TYPES
-----------------------------------
Ticket ID                         int64
Customer Name                    object
Customer Email                   object
Customer Age                      int64
Customer Gender                  object
Product Purchased                object
Date of Purchase                 object
Ticket Type                      object
Ticket Subject                   object
Ticket Description               object
Ticket Status                    object
Resolution                       object
Ticket Priority                  object
Ticket Channel                   object
First Response Time              object
Time to Resolution               object
Customer Satisfaction Rating    float64
dtype: object

UPDATED DATA TYPES
-----------------------------------
Ticket ID                                int64
Customer Name                           object
Customer Email                          object
Customer Age                             int64
Customer Gender                         object
Product Purchased                       object
Date of Purchase                datetime64[ns]
Ticket Type                             object
Ticket Subject                          object
Ticket Description                      object
Ticket Status                           object
Resolution                              object
Ticket Priority                         object
Ticket Channel                          object
First Response Time             datetime64[ns]
Time to Resolution              datetime64[ns]
Customer Satisfaction Rating           float64
dtype: object

**Summary:** Correct data types support reliable filtering, calculations, and time-based analysis. Values that cannot be converted become missing and should be reviewed.

# USABLE RECORDS

## Step 8: Usable Records Assessment

This cell checks whether essential ticket fields are present and counts complete and incomplete records.

In [9]:
# Identify essential columns for analysis
required_columns = [
    'Ticket ID',
    'Ticket Status',
    'Ticket Priority',
    'Ticket Type',
    'Ticket Channel'
]

# Check missing values in essential columns
print("MISSING VALUES IN ESSENTIAL COLUMNS")
print("-" * 40)
print(df[required_columns].isnull().sum())

# Count usable and incomplete records
usable_records = df[required_columns].notnull().all(axis=1)

print("\nUSABLE RECORDS:", usable_records.sum())
print("INCOMPLETE RECORDS:", (~usable_records).sum())
print("TOTAL RECORDS:", len(df))

MISSING VALUES IN ESSENTIAL COLUMNS
----------------------------------------
Ticket ID          0
Ticket Status      0
Ticket Priority    0
Ticket Type        0
Ticket Channel     0
dtype: int64

USABLE RECORDS: 8469
INCOMPLETE RECORDS: 0
TOTAL RECORDS: 8469

**Summary:** Records are assessed using Ticket ID, Ticket Status, Ticket Priority, Ticket Type, and Ticket Channel. No records are deleted in this step.

# DATA CLEANING

## Step 9: Data Cleaning

This cell creates a separate copy of the dataset, removes extra spaces from text values, and checks the cleaned result.

In [10]:
# Create a separate cleaned dataset
cleaned_df = df.copy()

# Remove unnecessary spaces from text columns
text_columns = cleaned_df.select_dtypes(include='object').columns

for col in text_columns:
    cleaned_df[col] = cleaned_df[col].str.strip()

# Check the cleaned dataset
print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", cleaned_df.shape)

print("\nRemaining duplicate rows:", cleaned_df.duplicated().sum())
print("Total missing values:", cleaned_df.isnull().sum().sum())

print("\nCleaned dataset preview:")
print(cleaned_df.head())

Original dataset shape: (8469, 17)
Cleaned dataset shape: (8469, 17)

Remaining duplicate rows: 0
Total missing values: 19919

Cleaned dataset preview:
   Ticket ID        Customer Name              Customer Email  Customer Age  \
0          1        Marisa Obrien  carrollallison@example.com            32
1          2         Jessica Rios    clarkeashley@example.com            42
2          3  Christopher Robbins   gonzalestracy@example.com            48
3          4     Christina Dillon    bradleyolson@example.org            27
4          5    Alexander Carroll     bradleymark@example.com            67

  Customer Gender Product Purchased Date of Purchase      Ticket Type  \
0           Other        GoPro Hero       2021-03-22  Technical issue
1          Female       LG Smart TV       2021-05-22  Technical issue
2           Other          Dell XPS       2020-07-14  Technical issue
3          Female  Microsoft Office       2020-11-13  Billing inquiry
4          Female  Autodesk AutoCAD       2020-02-04  Billing inquiry

             Ticket Subject  \
0             Product setup
1  Peripheral compatibility
2           Network problem
3            Account access
4                 Data loss

                                  Ticket Description  \
0  I'm having an issue with the {product_purchase...
1  I'm having an issue with the {product_purchase...
2  I'm facing a problem with my {product_purchase...
3  I'm having an issue with the {product_purchase...
4  I'm having an issue with the {product_purchase...

               Ticket Status                                     Resolution  \
0  Pending Customer Response                                            NaN
1  Pending Customer Response                                            NaN
2                     Closed   Case maybe show recently my computer follow.
3                     Closed  Try capital clearly never color toward story.
4                     Closed                    West decision evidence bit.

  Ticket Priority Ticket Channel First Response Time  Time to Resolution  \
0        Critical   Social media 2023-06-01 12:15:36                 NaT
1        Critical           Chat 2023-06-01 16:45:38                 NaT
2             Low   Social media 2023-06-01 11:14:38 2023-06-01 18:05:38
3             Low   Social media 2023-06-01 07:29:40 2023-06-01 01:57:40
4             Low          Email 2023-06-01 00:12:42 2023-06-01 19:53:42

   Customer Satisfaction Rating
0                           NaN
1                           NaN
2                           3.0
3                           3.0
4                           1.0

**Summary:** The original DataFrame is preserved, and no rows or missing values are removed or filled during this conservative cleaning step.